#!/bin/bash
set -e
EXPECTED_GRAILS_VERSION="2.0.3"
PLUGIN_NAME=$1

if [ -z "$PLUGIN_NAME" ]; then
	echo "You must supply a name for your plugin."
	exit 1
fi

echo "# Creating FrontlineSMS Plugin with name: $PLUGIN_NAME..."

if [ -d "$PLUGIN_NAME" ]; then
	echo "# Cannot create plugin as directory already exists."
	exit 1
fi

ACTUAL_GRAILS_VERSION=`grails -version | grep -E -o "[0-9]+(\.[0-9]+)*"`
if [ "$EXPECTED_GRAILS_VERSION" != "$ACTUAL_GRAILS_VERSION" ]; then
	echo "# Your grails version ($ACTUAL_GRAILS_VERSION) did not match required grails version ($EXPECTED_GRAILS_VERSION)"
	exit 1
fi

grails create-app $PLUGIN_NAME
cd $PLUGIN_NAME

echo "# inject required dependencies..."
DEPENDENCIES="provided ':frontlinesms-core:2.0-SNAPSHOT'"
sed -E -i -e "s/(^\s*plugins\s*\{\s*$)/\1\n\t\t$DEPENDENCIES/" grails-app/conf/BuildConfig.groovy

PLUGIN_NAME_CAPITALISED_CAMEL=`echo $PLUGIN_NAME | sed -r "s/[-\.](\w)/\U\1/g" | sed -r "s/(^|\s)(\w)/\1\U\2\E/g"`
PLUGIN_CLASS_NAME="${PLUGIN_NAME_CAPITALISED_CAMEL}GrailsPlugin"
GRAILS_PLUGIN_FILE="${PLUGIN_CLASS_NAME}.groovy"
echo "# creating plugin groovy file $GRAILS_PLUGIN_FILE..."
echo "class $PLUGIN_CLASS_NAME {
	def version = '0.1-SNAPSHOT'
	def grailsVersion = '2.0 > *'
	def dependsOn = [:]
	def pluginExcludes = [
		'grails-app/views/error.gsp'
	]
}
" >> $GRAILS_PLUGIN_FILE

cat << EOF
	Your FrontlineSMS2 Plugin $PLUGIN_NAME has been created.
	To package the plugin:
		$ grails package-plugin
EOF

